const LOADING_CURRENCIES = "LOADING_CURRENCIES" 
const FETCHED_CURRENCIES = "FETCHED_CURRENCIES"
const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST"
const ADD_TO_PORTFOLIO = "ADD_TO_PORTFOLIO"
const CHANGING_SEARCH_TEXT = "CHANGING_SEARCH_TEXT"
const SET_CURRENT_USER = "SET_CURRENT_USER"

export {LOADING_CURRENCIES, FETCHED_CURRENCIES , ADD_TO_PORTFOLIO , ADD_TO_WATCHLIST , CHANGING_SEARCH_TEXT , SET_CURRENT_USER} 