const CHANGING_SEARCH_TEXT = "CHANGING_SEARCH_TEXT"

// CURRENCIES
const LOADING_CURRENCIES = "LOADING_CURRENCIES" 
const FETCHED_CURRENCIES = "FETCHED_CURRENCIES"

// WATCHITEMS
const ADDED_WATCHITEM = "ADDED_WATCHITEM"
const LOADING_WATCHITEM = "LOADING_WATCHITEM"
const FETCHED_WATCHITEM = "FETCHED_WATCHITEM"
const DELETE_WATCHITEM = "DELETE_WATCHITEM"

// PORTFOLIO
const ADDED_TO_PORTFOLIO = "ADD_TO_PORTFOLIO"
const LOADING_PORTFOLIO = "ADDING_TO_PORTFOLIO"
const FETCHED_PORTFOLIO = "FETCHED_PORTFOLIO"
const DELETE_FRM_PORTFOLIO = "DELETE_FRM_PORTFOLIO"
const AMOUNT_INPUT = "AMOUNT_INPUT"

// USER
const SET_CURRENT_USER = "SET_CURRENT_USER"
const LOGGED_IN = "LOGGED_IN"
const LOGGED_OUT = "LOGGED_OUT" 
const CREATE_NEW_USER = 'CREATE_NEW_USER' 

export { LOADING_CURRENCIES, FETCHED_CURRENCIES , ADDED_TO_PORTFOLIO , ADDED_WATCHITEM ,LOADING_WATCHITEM , FETCHED_WATCHITEM ,
     DELETE_WATCHITEM , CHANGING_SEARCH_TEXT , SET_CURRENT_USER ,LOGGED_IN , LOGGED_OUT  , CREATE_NEW_USER , AMOUNT_INPUT  
     , LOADING_PORTFOLIO , FETCHED_PORTFOLIO , DELETE_FRM_PORTFOLIO } 


     