const LOADING_CURRENCIES = "LOADING_CURRENCIES" 
const FETCHED_CURRENCIES = "FETCHED_CURRENCIES"
const ADDED_TO_WATCHLIST = "ADDED_TO_WATCHLIST"
const ADDED_TO_PORTFOLIO = "ADDED_TO_PORTFOLIO"

export {LOADING_CURRENCIES, FETCHED_CURRENCIES , ADDED_TO_PORTFOLIO , ADDED_TO_WATCHLIST} 